name: flutter_news_web
description: A new Flutter project.

dependencies:
  http: "^0.11.3+16"
  flutter:
    sdk: flutter
  flutter_webview_plugin: ^0.2.1+2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  barcode_scan: ^1.0.0

dev_dependencies:
  
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - images/business_news.png
    - images/entertainment_news.png
    - images/health.jpg
    - images/health_news.png
    - images/no_image_available.png
    - images/politics_news.png
    - images/science_news.png
    - images/sports_news.png
    - images/tech_news.png
    - images/top_news.png
    - images/qricon.png
    - images/products.png
    - images/champion.png
    - images/nuts.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
